### ISSUE TITLE
Vanara.Windows.Shell.ShellItemChangeWatcher - System.AccessViolationException

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#124]
**Describe the bug**
Hello I'm getting System.AccessViolationException when using ShellItemChangeWatcher.
May happen immediatly or after few events were received.
* OS: Windows 10

**Stack trace**

> Exception of type 'System.AccessViolationException' in Vanara.PInvoke.Shell32.dll
   in Vanara.PInvoke.Shell32.IntILClone(IntPtr pidl)
   in Vanara.PInvoke.Shell32.PIDL..ctor(IntPtr pidl, Boolean clone, Boolean own)
   in Vanara.Windows.Shell.ShellItemChangeWatcher.ShellItemChangeEventArgs..ctor(SHCNE levent, IntPtr rgpidl)
   in Vanara.Windows.Shell.ShellItemChangeWatcher.WatcherNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**What code is involved**
```cs
[STAThread]
private static void Main(string[] args)
{
	var pidl = Shell32.KNOWNFOLDERID.FOLDERID_RecycleBinFolder.PIDL();
	var shellItem = new ShellItem(pidl);
	var watcher = new ShellItemChangeWatcher(shellItem, false);
	watcher.Changed += Watcher_Changed;
	watcher.EnableRaisingEvents = true;
	...
}

private static void Watcher_Changed(object sender, ShellItemChangeWatcher.ShellItemChangeEventArgs e)
{            
	Console.WriteLine($"File: {string.Join(", ",e.ChangedItems.Select(i => i.Name))} {e.ChangeType}"); -------> exception
}
```

**Comment by dahall** [comment]
I think I found the bug. I have tested this on a few files and directories with many changes without errors. It is building now and should be ready from the AppVeyor NuGet feed shortly if you'd like to test. See home page readme for details.

**Comment by gave92** [comment]
Hello thanks for looking into this. I'm still getting the same exception unless I do this:
```watcher.NotifyFilter = ChangeFilters.AllDiskEvents;```
With this I get the AccessViolationExpception when I e.g. delete multiple files from the recycle bin which I'm watching
```watcher.NotifyFilter = ChangeFilters.AllEvents;``` 
But for my use case AllDiskEvents is fine.

**Comment by dahall** [comment]
Are you saying there are two problems still? 1) Exceptions when `NotifyFilter` is not `AllDiskEvents` and 2) `AccessViolation` when you delete multiple files?

**Comment by gave92** [comment]
The original issue is still present when NotifyFilter is AllEvents (with AllDiskEvents the issue does not happen). An reproducible way to get that exception is to watch the recycle bin and delete a few files from it.

**Comment by dahall** [comment]
I just pushed another update that I think has resolved the issues. I've tested as you indicated without errors. I also updated the version to 3.2.9 so the NuGet packages from AppVeyor should be easier to find. Let me know what you find.

**Comment by gave92** [comment]
Thanks I've tested 3.2.9 but the problem when NotifyFilter is AllEvents is still present.

**Stack trace**
> System.AccessViolationException
  HResult=0x80004003
   in Vanara.PInvoke.Shell32.SHCreateItemFromIDList(PIDL pidl, Guid& riid, Object& ppv)
   in Vanara.Windows.Shell.ShellItemChangeWatcher.ShellItemChangeEventArgs.<>c__DisplayClass0_0.<<-ctor>g__GetItems|0>d.MoveNext()
   in System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   in System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   in Vanara.Windows.Shell.ShellItemChangeWatcher.ShellItemChangeEventArgs..ctor(SHCNE levent, IntPtr rgpidl)
   in Vanara.Windows.Shell.ShellItemChangeWatcher.WatcherNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by dahall** [comment]
So I just added a lot of checks. Hopefully this works. It should be built in about 10 minutes on AppVeyor.

**Comment by gave92** [comment]
I can confirm the fix works! Closing this.

**Comment by gave92** [comment]
The issue seems to be resolved. I'm not getting the exception event with the AllEvents filter.

**Comment by gave92** [comment]
I'm writing here even if I don't think this is an issue of the library but with Win32.
I'm getting very inconsistent results from using ShellItemChangeWatcher: some times when I create/delete a file I get the proper "ItemCreated/ItemDeleted" event. Many other times instead I only see an "ExtendedEvent" or "DiskFreeSpaceChanged" event.
Do you happen to know why is that or how to resolve this?

**Comment by dahall** [comment]
I saw the same during my testing and found a couple posts with people claiming the same problem. I do think it is Win32 and those posts did not have any resolution.
