### ISSUE TITLE
AccessViolation Exception on VirtDisk.SetVirtualDiskInformation (only x64)

### ISSUE THREAD

**Issue by elf2k00** [dahall/Vanara#284]
**Describe the bug**
When calling the PInvoke VirtDisk.SetVirtualDiskInformation method changing ParentFilePath configuration, using a StrPtrUni pointer, and access violation is thrown in x64 compilation, in x86 works as expected and ParentFilePath is changed. Passing null as value does not throw an exception in x64.

**What code is involved**
```cs
using static Vanara.PInvoke.VirtDisk;

OPEN_VIRTUAL_DISK_FLAG flags =  OPEN_VIRTUAL_DISK_FLAG.OPEN_VIRTUAL_DISK_FLAG_NO_PARENTS;
OPEN_VIRTUAL_DISK_PARAMETERS param = new OPEN_VIRTUAL_DISK_PARAMETERS(false, false);

Win32Error ret = OpenVirtualDisk(new VIRTUAL_STORAGE_TYPE(), file_path,
    VIRTUAL_DISK_ACCESS_MASK.VIRTUAL_DISK_ACCESS_NONE,
    flags, param, out var _handle);                

SET_VIRTUAL_DISK_INFO setInfo = new SET_VIRTUAL_DISK_INFO();
setInfo.Version = SET_VIRTUAL_DISK_INFO_VERSION.SET_VIRTUAL_DISK_INFO_PARENT_PATH;
setInfo.ParentFilePath = new StrPtrUni(@"C:\Temp\disk.vhdx" + '\0');

ret = SetVirtualDiskInformation(_handle, in setInfo);
```
**Expected behavior**
No exception should be thrown in x64.

**Comment by dahall** [comment]
Thank you for the report.

First, I'd encourage you to look at the `Vanara.VirtualDisk` package which wraps all the `VirtDisk` functions. Much simpler. For example, you can do the above with:
```cs
using Vanara.IO;

using var disk = VirtualDisk.Open(file_path, readOnly: false, getInfoOnly: false, noParents: true);
disk.SetParentPath(@"C:\Temp\disk.vhdx");
```

That said, in order to get sizing to work in an X64 build, you must create a build constant "X64". The `[\Directory.Build.targets](https://github.com/dahall/Vanara/blob/600d50bf0cad6a575f35b7eef2b894787b68efa5/Directory.Build.targets#L7)' file does this for you, but if you are building in a different way, you must do that in your project file.

Let me know if that doesn't fix your issue.

**Comment by elf2k00** [comment]
Thank you for the answer. I'll try the directory.build.targets x64 configuration.

I cannot find SetParentPath method in Virtualdisk.
Please note that not all methods present in virtdisk.h and declared in Vanara.PInvoke.VirtDisk are present in Vanara.VirtualDisk, for example these methods are not wrapped and must be used directly:

- SetVirtualDiskInformation (with this method you can set a new Parent path)
- GetStorageDependencyInformation

**Comment by dahall** [comment]
I just committed the addition of SetParentPath and SetParentPathWithDepth methods to VirtualDisk. You'll find them in the next release or in the current pull from AppVeyor (see homepage for details). I'm working on the addition of GetStorageDependencyInformation, but am finding it a little more difficult. If you have working code, I'd appreciate it.

One note, your code use of StrPtrUni will produce a memory leak. Use the following instead:
```cs
using var pStr = new SafeCoTaskMemString(@"C:\Temp\disk.vhdx");
setInfo.ParentFilePath = (IntPtr)pStr;
```

**Comment by dahall** [comment]
There were some big problems with the implementation of `VirtDisk.GetStorageDependencyInformation`. I just committed the fix along with a static method in `VirtualDisk.GetStorageDependencyInformation` that simply gets the array of results. Thanks for making me look at these. You can get the current build from the AppVeyor NuGet repo (see homepage) or wait a few days and I'll push to NuGet.org.

**Comment by elf2k00** [comment]
I was just trying to make GetStorageDependencyInformation work and just read your message, the structures relative to STORAGE_DEPENDENCY_INFO where returning a size of 12 bytes instead of 56 making even the first call to fail with INVALID_PARAMETER.

I have tested the changes you made (big changes!) with several parent disks and children involved and works as expected.
Great job!

**Comment by dahall** [comment]
Awesome. Thanks for the feedback. Were you using the raw PInvoke functions or the VirtualDisk class?

**Comment by elf2k00** [comment]
I applied the changes you commited in VirtualDisk class until the nuget package is updated.

**Comment by dahall** [comment]
I just committed a number of additions to the `VirtualDisk` class and the new pre-release packages are available on AppVeyor. I'd really appreciate it if you could run your tests against this code. I did a lot more testing and changed properties so if they are specific to a state (attached or differencing) they are nullable now and just return `null` if the state doesn't allow retrieval. A few method parameters changed as well. I know it may break existing code, but it is much less prone to exceptions now.

Adding https://ci.appveyor.com/nuget/vanara-prerelease to your NuGet sources will give you access to the new packages. I plan to publish in a few days and hope to have your feedback before I do. Thanks!

**Comment by dahall** [comment]
I'd also be interested to know if you have any enhancement requests for `VirtualDisk` or items from your codebase that would be valuable to others. :)

**Comment by elf2k00** [comment]
Sure, just give me a couple of days to run all the tests on the prerelease version. I'm currently running these VirtDisk operations: 

GetAllAttachedVirtualDiskPaths, Metadata Add and Get, Attach, Detach, Open (to get info and RW ops), Close, SetVirtualDiskInformation, GetDependencyInfoByVolume.

I'll start using other operations in the coming weeks.

As an enhancement:

I found challenging how to get the assigned drive letters for an already mounted vhdx, something that can be easily achieved in powershell or diskpart.

The approach I followed:
With the physical drive property, loop throughout all the mounted Unit Drives (C:\,D:\..) and with a call to DeviceIOControl with Control IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS match the Unit Drive disk number with the physical drive disk number from the VHDX.

Another approach but only valid for a vhdx you are attaching:
you can attach it with the flag ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER, then loop all volumes with FindFirstVolume/FindNextVolume calls and match again the disk number, and finally mount it with SetVolumeMountPoint.

**Comment by dahall** [comment]
Thank you. I'm curious what property you're setting with `SetVirtualDiskInformation`. I thought I'd covered them all.

I'll work on incorporating the drive letter assignment.

**Comment by dahall** [comment]
Lots more updates today, including those you requested around mount points. You can now specify a mount drive or folder when calling AttachAsync and discover their details in VolumeGuidPath and VolumeMountPoint properties.

**Comment by elf2k00** [comment]
Looking forward to trying the new mount points details!.

> I'm curious what property you're setting with SetVirtualDiskInformation

It's `SetParentPath`, it's already covered, I was using directly  `SetVirtualDiskInformation ` until you implemented the method.

I have run several tests with 4.4.1 version in different scenarios with no issues (parent and several children relationship, attached or not attached vhdx), these are the methods I have tested:

`Open` readonly and getinfo, true and false 
`Attach`
Metadata, `Add `and `TryGetValue `values
`GetStorageDependencyInformation`
`GetAllAttachedVirtualDiskPaths`
`SetParentPath`

I haven't started with Merging or Creation methods yet.

**Comment by elf2k00** [comment]
Hello,
I've been testing the mount points details in VirtualDisks, please note that a single vhdx can have several volumes and mount points.

![Capture](https://user-images.githubusercontent.com/101286526/166514892-218a6534-89ad-42a3-8823-a4bcc7de96a4.PNG)


The new VolumeGuidPath and VolumeMountPoint properties should support several drives.

This function just modifies the `FirstOrDefault `from the code and gets all Volume Guids for the disk number:

`private static string[] GetVolumeGuidFromDiskNumber(uint diskNo) => EnumVolumes().Where(v =>
        {
            using var hfile = OpenDrive(v.TrimEnd('\\'));
            return !hfile.IsInvalid &&
                DeviceIoControl(hfile, IOControlCode.IOCTL_STORAGE_GET_DEVICE_NUMBER, out STORAGE_DEVICE_NUMBER output) &&
                output.DeviceNumber == diskNo;
        }).ToArray();`

These `string `properties should be replaced by string arrays

 `string[] VolumeGuidPath ` 
`string[] VolumeMountPoint`

Other methods are affected with this change:

`public string[] VolumeMountPoint
	{
		get
		{
			var volPath = VolumeGuidPath;
			return volPath is null ? null : GetVolumeMountPoints(volPath);
		}
	}`

`public string[] VolumeGuidPath`


The `Attach` method with the option to specify a drive letter should also be able to accept a `string[]` parameter with all the drives letters for all the volumes present in the vhdx. Something like this, if the drive letters provided in the call are less than the actual volumes in the vhdx, these volumes will not have an assigned drive letter (the same that happens now), but it's not possible to specify one specific volume guid to be mounted.


`
public static void Attach(string[] mountPoint, bool readOnly = false, bool autoDetach = true, FileSecurity access = null)
 {

  ATTACH_VIRTUAL_DISK_FLAG flags = readOnly ? ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY : 0;

            if (!autoDetach)
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME;

            if (mountPoint is null || mountPoint.Length == 0)
                throw new ArgumentException();
            if (mountPoint[0] != "*")
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER;
            if (access is null)
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_SECURITY_DESCRIPTOR;

            ATTACH_VIRTUAL_DISK_PARAMETERS param = ATTACH_VIRTUAL_DISK_PARAMETERS.Default;
            using SafePSECURITY_DESCRIPTOR sd = FileSecToSd(access);
            Attach(flags, param, sd);
            if (mountPoint[0] is not "*")
            {
                for (int i = 0; i < mountPoint.Length;i++)
                    Win32Error.ThrowLastErrorIfFalse(SetVolumeMountPoint(mountPoint[i], VolumeGuidPath[i]));
            }
        }`

**Comment by dahall** [comment]
Thanks. I ended up with a slight variation to break less existing code:
1) Added `VolumeGuidPaths` and `VolumeMountPoints` properties to provide access to multiple values
2) Created `Attach` overload that takes `string[]` as first param, but implemented it so that passing `null` assigns no drives and error checks to ensure that only single enty of "*" will have system assign drive.

I have checked in the `VirtualDisk.cs` file and appreciate your review.

**Comment by elf2k00** [comment]
Hello, there's an error in this sentence from the new `Attach` method

`		if (mountPoints.Length == 1 && mountPoints[0] != "*")`
			`flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER;`

should be:

`if (mountPoints.Length > 0 && mountPoints[0] != "*")`
                    `flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER;`

This way all this calls to the attach method work as expected:

`Attach("M:\\", false);`
`Attach(new[] {"M:\\", "N:\\"}, false);`
 `Attach(new[] { "M:\\" }, false);`

**Comment by dahall** [comment]
I think I had two logic problems. Please check my work on latest commit. The XML docs for the method describe the use of the `mountPoints` parameter.

**Comment by elf2k00** [comment]
There's a problem with the new version.
When you call the `Attach` method you need the `VolumeGuidPaths` to have a not null value, but for that you need the vhdx to be attached and have the `physicaldisk` property already with a value.

I think you'd need to call the `Attach(flags, param, sd);` before using the `vgp` (VolumeGuidPaths) value for this to work.

Also please note that when you pass one or several mount points to the Attach method, the flag `ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER` should be used, otherwise the volumes will be mounted with the default drive letters and later the call to `SetVolumeMountPoint` will have no effect.

Please find below a working sample:

`public static void Attach(string[] mountPoints, bool readOnly = false, bool autoDetach = true, FileSecurity access = null)`
        `{`
            `ATTACH_VIRTUAL_DISK_FLAG flags = 0;`
            `if (mountPoints is null || (mountPoints.Length > 0 && mountPoints[0] != "*"))
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER;`
            `if (readOnly)
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY;`
           ` if (!autoDetach)
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME;`
            `if (access is null)
                flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_SECURITY_DESCRIPTOR;`

            ATTACH_VIRTUAL_DISK_PARAMETERS param = ATTACH_VIRTUAL_DISK_PARAMETERS.Default;
            using SafePSECURITY_DESCRIPTOR sd = FileSecToSd(access);
            Attach(flags, param, sd);

            var vgp = VolumeGuidPaths;
            if (mountPoints is not null && (mountPoints.Length == 0 || mountPoints.Length > vgp.Length || (mountPoints[0] != "*" && mountPoints.Any(p => p == "*"))))
            {
                v.Detach();
                throw new ArgumentException(null, nameof(mountPoints));
            }

            if (mountPoints is null || mountPoints[0] is "*") return;
            for (var i = 0; i < mountPoints.Length; i++)
                Win32Error.ThrowLastErrorIfFalse(SetVolumeMountPoint(mountPoints[i], vgp[i]));
        }`


With this function these calls are succesful for a vhdx with 1 or several volumes:

`Attach(new[] { "M:\\"});`
            `Attach(new[] { "M:\\", "N:\\"});`
            `Attach("*");`

Please note that a call with a null value would be ambiguous between Attach(string) and Attach(string[]) param
`Attach(null);`

**Comment by dahall** [comment]
Damn. I thought I'd gotten that right. Thanks for checking it. I'll get it fixed and re-released.

**Comment by dahall** [comment]
What's the logic in checking conditions after attaching and detaching on failure rather than just checking before attaching?

What do you think about removing the mount point from the `Attach(string...` method so it always behaves like the `Attach(new string[] { "*" }...` overload? That will take care of the ambiguous call.

**Comment by dahall** [comment]
Please check my logic on the following:
```cs
public void Attach(string[] mountPoints, bool readOnly = false, bool autoDetach = true, FileSecurity access = null)
{
   if (mountPoints is not null && (mountPoints.Length == 0 || (mountPoints[0] != "*" && mountPoints.Any(p => p == "*"))))
      throw new ArgumentException(null, nameof(mountPoints));

   ATTACH_VIRTUAL_DISK_FLAG flags = 0;
   if (mountPoints is null || (mountPoints.Length > 0 && mountPoints[0] != "*"))
      flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER;
   if (readOnly)
      flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY;
   if (!autoDetach)
      flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME;
   if (access is null)
      flags |= ATTACH_VIRTUAL_DISK_FLAG.ATTACH_VIRTUAL_DISK_FLAG_NO_SECURITY_DESCRIPTOR;

   ATTACH_VIRTUAL_DISK_PARAMETERS param = ATTACH_VIRTUAL_DISK_PARAMETERS.Default;
   using SafePSECURITY_DESCRIPTOR sd = FileSecToSd(access);
   Attach(flags, param, sd);

   if (mountPoints is null || mountPoints[0] is "*")
      return;

   var vgp = VolumeGuidPaths;
   if (mountPoints.Length > vgp.Length)
   {
      Detach();
      throw new ArgumentException(null, nameof(mountPoints));
   }
   for (var i = 0; i < mountPoints.Length; i++)
      Win32Error.ThrowLastErrorIfFalse(SetVolumeMountPoint(mountPoints[i], vgp[i]));
}
```

**Comment by elf2k00** [comment]
Perfect!, all my tests work as expected with the new method.

As you said, I'd use a string[] param, also for properties `VolumeGuidPaths `and `VolumeMountPoints` removing the string `VolumeGuidPath` `VolumeMountPoint `properties

**Comment by dahall** [comment]
I just committed the changes and the NuGet packages should be available shortly on the AppVeyor feed.

**Comment by elf2k00** [comment]
Hello again,
I can see you have updated the packages in [appveyor repository](https://ci.appveyor.com/nuget/vanara-prerelease) but I cannot find the latest changes, I'm still seeing the version with the `string mountPoint` and `string[] mountPoints` and some logic bugs when I inspect the code in the downloaded DLLs. It's version 3.4.2. 

It looks like new Vanara.VirtualDisk hasn't been commited, can you confirm it?

**Comment by dahall** [comment]
See this [commit](https://github.com/dahall/Vanara/commit/847f8b9e12c00aca5d89e38443dd5c61f34c8f4a)

**Comment by elf2k00** [comment]
But the installed and compiled Vanara.VirtualDisk.dll v3.4.2 downloaded from [appveyor](https://ci.appveyor.com/nuget/vanara-prerelease) still has the version from 6 days ago, not the new one.

In nuget.org the available version is 3.4.1
I tried from scratch with a new project in case the DLLs were cached.

**Comment by dahall** [comment]
I just pulled 3.4.2 from AppVeyor and it is the latest. Make sure you remove the package, then clear the NuGet caches, then re-add the package to get the latest from the server.
